### ISSUE TITLE
Custom component configuration is not removed when a component is removed

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1798]
**Describe the bug**
After the removal of a component, the framework doesn't check if the custom component configuration in `aea-config.yaml` has been removed.

**To Reproduce**
- Create an agent and add the echo skill
```
aea create myagent && cd myagent
aea add skill fetchai/echo
```
- Append the following text snippet to `aea-config.yaml`:
```
---
name: echo
author: fetchai
version: 0.8.0
type: skill
behaviours:
  echo:
    args:
      tick_interval: '2.0'
```
- `aea remove skill fetchai/echo`
- try to run the agent.

**Expected behavior**
The agnet runs as expected.

**Actual Behaviour**
```Error: Component (skill, fetchai/echo:0.8.0) not declared in the agent configuration.```

**Screenshot**
n/a

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser n/a
 - Version `aea > 0.6.2` (`develop` version)

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a
