### ISSUE TITLE
Use id as key for resources list in skill.yaml

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#205]
**Is your feature request related to a problem? Please describe.**

skill.yaml file format is not very handy when listing different components, e.g.

```
...
handlers:
    handler:
        - field1
        - field2
    handler:
        - field1
        - field2
... # the same for other component types
```

**Describe the solution you'd like**

Instead of repeating `handler:`, we could use its identifier, e.g.

```
...
handlers:
    handler1:
        - field1
        - field1
        - field2
    handler2:
        - field1
        - field2
... # the same for other component types
```

**Describe alternatives you've considered**

None.

**Additional context**

None
