### ISSUE TITLE
Upgrade coin_price skill to make more general

### ISSUE THREAD

**Issue by jrriehl** [fetchai/agents-aea#2230]
**Is your feature request related to a problem? Please describe.**
There is some duplicate functionality between the `coin_price` and `simple_data_request` skills. Also, the `coin_price` skill could quite easily be generalized.

**Describe the solution you'd like**
Instead of hard-coding the CoinGecko API spec in the `coin_price` HttpHandler, the config could include the json path for desired data from the specified url. For example:
```yaml
models:
  data_request_model:
    args:
      url: https://api.coingecko.com/api/v3/simple/price?ids={coin_id}&vs_currencies={currency}
      inputs:
        coin_id: fetch-ai
        currency: usd
      output_json_paths:
        price: [{coin_id}][{currency}]
      use_http_server: false
    class_name: DataRequestModel
```
and the shared_state key names would be set from the keys in `output_json_paths`. This would make the skill generalize to arbitrary API data requests, similar to `simple_http_request` but with a bit of added functionality.

**Describe alternatives you've considered**
These features could be added as an upgrade to either the `coin_price` or `simple_data_request` skills. The latter case would effectively make the `coin_price` skill obsolete.

**Additional context**
The `coin_price` skill currently has the capability to serve requests via the `http_server` connection and allows monitoring via the `prometheus` connection. For these reasons, we might want to keep `simple_data_request` as is, without the extra features, but if we want to minimize duplicated functionality across skills, it might make sense to include everything in one skill.
