### ISSUE TITLE
Allow for reference of origin in dependency specs

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#477]
**Is your feature request related to a problem? Please describe.**
Currently, the dependencies listed in .yaml files are fetched from PyPi.

**Describe the solution you'd like**
Allow for the origin to be specified (git and test-pypi) similar to a Pipfile

**Comment by marcofavorito** [comment]
Should it be:
```yaml
dependencies:
  - colorlog:
        index: https://test.pypi.org/simple
        version: 0.1.0
  - oef:
        git: "https://github.com/fetchai/oef-sdk-python.git"
        ref: v0.8.1
```
or
```yaml
dependencies:
  - dependency:
        name: colorlog 
        index: https://test.pypi.org/simple
        version: 0.1.0  
- dependency:
        name: oef
        ref: v0.8.1
        git: "https://github.com/fetchai/oef-sdk-python.git"
```

Notice that in the former is still possible to constrain packages name to a regular expression:
[https://stackoverflow.com/a/41885699](https://stackoverflow.com/a/41885699)

Other ideas?
