### ISSUE TITLE
Option to set all configs from `aea-config.yaml`

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#798]
**Is your feature request related to a problem? Please describe.**
Currently, configs need to be set at each level.

**Describe the solution you'd like**
Allow for an override option where configs set on top level (`aea-config.yaml`) override all the configs in the packages. This way, an `aea-config.yaml` fully specifies an agent.

**Comment by DavidMinarsch** [comment]
Ideally something like a multi-page yaml doc:

```
aea_version: ">=0.2.0"
agent_name: myagent
author: fetchai
version: 0.1.0
license: Apache-2.0
fingerprint: {}
connections:
- fetchai/oef:0.1.0
default_connection: fetchai/oef:0.1.0
default_ledger: fetchai
private_key_paths: {}
protocols:
- fetchai/oef_search:0.1.0
- fetchai/default:0.1.0
- fetchai/tac:0.1.0
- fetchai/fipa:0.1.0
skills:
- fetchai/echo:0.1.0
description: "An example of agent configuration file for testing purposes."
logging_config:
  disable_existing_loggers: false
  version: 1
registry_path: ../../packages
ledger_apis:
   fetchai:
     args:
       address: example.fetch-ai.com
       port: 8080
   ethereum:
     args:
       address: example.ethereum.com
       chain_id: 8080
---
name: dummy
author: dummy_author
version: 0.1.0
description: a dummy_skill for testing purposes.
license: Apache-2.0
aea_version: '>=0.2.0, <0.3.0'
fingerprint:
  __init__.py: Qmd3mY5TSBA632qYRixRVELXkmBWMZtvnxJyQC1oHDTuEm
  behaviours.py: QmWKg1GfJpuJSoCkEKW1zUskkNo4Rsoan1AD2cXpe2E93C
  dummy.py: QmeV6FBPAkmQC49gATSmU1aq8S1SKPv7cm2zSH8cnuqoLT
  handlers.py: QmVe1VGT7TBdjQ5xG8X9djY77f8hebHeUeX3eDrQ6FR3yt
  tasks.py: Qmegg4QsYSqSZN3q2zuRiBAToQ2LEiWrAPtUo7rCMrxjGJ
fingerprint_ignore_patterns: []
contracts: []
protocols:
- fetchai/default:0.1.0
behaviours:
  dummy:
    args:
      behaviour_arg_1: 1
      behaviour_arg_2: '2'
    class_name: DummyBehaviour
handlers:
  dummy:
    args:
      handler_arg_1: 1
      handler_arg_2: '2'
    class_name: DummyHandler
  dummy_internal:
    args:
      handler_arg_1: 1
      handler_arg_2: '2'
    class_name: DummyInternalHandler
models:
  dummy:
    args:
      model_arg_1: 1
      model_arg_2: '2'
    class_name: DummyModel
dependencies: {}
...
```
Then one can IPFS hash this and use the single hash to run an AEA like so: `aea run IPFSHASH` which will build the AEA and then run it.
